# network architecture

# frontend related
frontend: default
frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160

# encoder related
encoder: vgg_rnn
encoder_conf:
    rnn_type: lstm     # encoder architecture type
    bidirectional: True
    use_projection: True
    num_layers: 4
    hidden_size: 1024
    output_size: 1024

# decoder related
decoder: rnn
decoder_conf:
    num_layers: 2
    hidden_size: 1024
    sampling_probability: 0
    att_conf:
        atype: location
        adim: 1024
        aconv_chans: 10
        aconv_filts: 100

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.5

# minibatch related
batch_size: 30

# optimization related
optim: adadelta
max_epoch: 15
patience: 3


# minibatch related
batch_type: numel
batch_bins: 10000000

best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10



specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
